# Generated by Django 3.2.3 on 2021-05-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField(max_length=255)),
                ('Date_Time', models.IntegerField()),
                ('Event_location', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=2500)),
            ],
        ),
    ]
