# Generated by Django 3.2.3 on 2021-05-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='Event_Description',
            field=models.CharField(default=1000, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventpage',
            name='max_participants',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='Date_Time',
            field=models.DateTimeField(),
        ),
    ]
