# Generated by Django 3.2.3 on 2021-05-24 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0003_alter_eventpage_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='Date_Time',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='Time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
